version: "3.7"

services:
  review-review-web:
    container_name: review-review-web
    image: review-review-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4200:4200
      - 9876:9876
    restart: unless-stopped
